# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 10:02
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('billingpostalcode', models.CharField(blank=True, max_length=20, null=True)),
                ('isdeleted', models.BooleanField(default=False)),
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('billinglatitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('_hc_lastop', models.CharField(blank=True, max_length=32, null=True)),
                ('createddate', models.DateTimeField(blank=True, null=True)),
                ('billingcountry', models.CharField(blank=True, max_length=80, null=True)),
                ('geolocation_longitude_s', models.DecimalField(blank=True, db_column='geolocation__longitude__s', decimal_places=8, max_digits=11, null=True)),
                ('geolocation_latitude_s', models.DecimalField(blank=True, db_column='geolocation__latitude__s', decimal_places=8, max_digits=11, null=True)),
                ('billingstate', models.CharField(blank=True, max_length=80, null=True)),
                ('billingstreet', models.CharField(blank=True, max_length=255, null=True)),
                ('billinglongitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('billingcity', models.CharField(blank=True, max_length=40, null=True)),
                ('systemmodstamp', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('_hc_err', models.TextField(blank=True, max_length=1024, null=True)),
                ('sfid', models.CharField(blank=True, max_length=18, null=True)),
            ],
            options={
                'verbose_name': 'Salesforce Account',
                'db_table': 'salesforce"."account',
                'managed': False,
                'verbose_name_plural': 'Salesforce Accounts',
            },
        ),
        migrations.CreateModel(
            name='AccountAddon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('avg_consumer_spending', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('menu_best_sellers', models.TextField(blank=True, null=True)),
                ('promotions', models.TextField(blank=True, null=True)),
                ('last_update_datetime', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('is_type', models.CharField(default='Account', max_length=50)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accountaddons', to='accounts.Account')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myuser.MyUser')),
            ],
            options={
                'db_table': 'cms_account_addon',
                'verbose_name_plural': 'Account Addons',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=200)),
                ('correct_answer', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='contests.Contest')),
            ],
            options={
                'db_table': 'cms_answer',
            },
        ),
    ]
