# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Salesforce Account', 'verbose_name_plural': 'Salesforce Accounts'},
        ),
    ]
